import type { WorkspaceData } from "./types";

export const demoWorkspace: WorkspaceData = {
  source: "demo",
  organizations: [
    { id: "org-1", name: "North Grid Authority", contactEmail: "ops@northgrid.local", departmentCount: 2 },
    { id: "org-2", name: "Metro Delivery Unit", contactEmail: "delivery@metro.local", departmentCount: 2 },
  ],
  departments: [
    { id: "dept-1", organizationId: "org-1", name: "Platform", code: "PLT", capacityUtilization: 82 },
    { id: "dept-2", organizationId: "org-1", name: "Operations", code: "OPS", capacityUtilization: 74 },
    { id: "dept-3", organizationId: "org-2", name: "Design Systems", code: "DSN", capacityUtilization: 63 },
    { id: "dept-4", organizationId: "org-2", name: "Field Enablement", code: "FLD", capacityUtilization: 91 },
  ],
  projects: [
    {
      id: "prj-1",
      departmentId: "dept-1",
      projectCode: "PM-101",
      name: "Vayu Node Stabilization",
      description: "Deep-dive remediation across gateway, telemetry, and workflow nodes.",
      status: "InProgress",
      priority: "Critical",
      progressPercentage: 68,
      aiHealthScore: 74,
      aiDelayRiskScore: 42,
      plannedEndDate: "2026-06-15",
      projectManagerName: "Asha Kapoor",
      totalTasks: 8,
      completedTasks: 4,
      overdueTasks: 1,
    },
    {
      id: "prj-2",
      departmentId: "dept-2",
      projectCode: "PM-207",
      name: "Command Center Migration",
      description: "Shift operations dashboard to resilient multi-region infrastructure.",
      status: "Delayed",
      priority: "High",
      progressPercentage: 44,
      aiHealthScore: 58,
      aiDelayRiskScore: 79,
      plannedEndDate: "2026-06-28",
      projectManagerName: "Mira Joshi",
      totalTasks: 6,
      completedTasks: 2,
      overdueTasks: 2,
    },
    {
      id: "prj-3",
      departmentId: "dept-3",
      projectCode: "PM-311",
      name: "Unified UI System",
      description: "Compact project, milestone, task, and subtask interfaces for PMWDS.",
      status: "InProgress",
      priority: "Medium",
      progressPercentage: 57,
      aiHealthScore: 83,
      aiDelayRiskScore: 24,
      plannedEndDate: "2026-07-05",
      projectManagerName: "Sara Rao",
      totalTasks: 7,
      completedTasks: 3,
      overdueTasks: 0,
    },
  ],
  milestones: [
    {
      id: "ms-1",
      projectId: "prj-1",
      name: "Telemetry Baseline",
      description: "Confirm core metric streams and incident thresholds.",
      dueDate: "2026-05-31",
      status: "Completed",
      isCritical: true,
      progressPercentage: 100,
    },
    {
      id: "ms-2",
      projectId: "prj-1",
      name: "Gateway Recovery",
      description: "Patch timeout handling and retry policy across entry services.",
      dueDate: "2026-06-10",
      status: "InProgress",
      isCritical: true,
      progressPercentage: 64,
    },
    {
      id: "ms-3",
      projectId: "prj-2",
      name: "Migration Dry Run",
      description: "Run migration rehearsal against replicated operations data.",
      dueDate: "2026-06-12",
      status: "Delayed",
      isCritical: false,
      progressPercentage: 36,
    },
    {
      id: "ms-4",
      projectId: "prj-3",
      name: "Interaction Model",
      description: "Compact expansion, comments, progress controls, and detail modals.",
      dueDate: "2026-06-07",
      status: "InProgress",
      isCritical: false,
      progressPercentage: 72,
    },
  ],
  tasks: [
    {
      id: "task-1",
      projectId: "prj-1",
      milestoneId: "ms-2",
      title: "Normalize gateway retry policy",
      description: "Apply consistent backoff and capture failure reasons for support teams.",
      status: "InProgress",
      priority: "Critical",
      progressPercentage: 60,
      dueDate: "2026-06-04",
      assignedToUserId: "u-1",
      assignedToUserName: "Asha Kapoor",
      comments: [
        {
          id: "c-1",
          taskId: "task-1",
          userId: "u-2",
          content: "Retry policy reviewed with operations. Waiting on final threshold values.",
          createdDate: "2026-05-23T09:00:00Z",
        },
      ],
      subTasks: [
        {
          id: "sub-1",
          parentTaskId: "task-1",
          projectId: "prj-1",
          milestoneId: "ms-2",
          title: "Document timeout classes",
          status: "Completed",
          priority: "Medium",
          progressPercentage: 100,
          dueDate: "2026-05-27",
          comments: [],
        },
        {
          id: "sub-2",
          parentTaskId: "task-1",
          projectId: "prj-1",
          milestoneId: "ms-2",
          title: "Patch retry middleware",
          status: "InProgress",
          priority: "Critical",
          progressPercentage: 55,
          dueDate: "2026-06-02",
          comments: [
            {
              id: "c-sub-1",
              taskId: "sub-2",
              userId: "u-1",
              content: "Middleware patch is staged behind feature flag.",
              createdDate: "2026-05-24T08:30:00Z",
            },
          ],
        },
      ],
    },
    {
      id: "task-2",
      projectId: "prj-2",
      milestoneId: "ms-3",
      title: "Validate migration rollback",
      description: "Confirm rollback steps and owner handoff for failed dry run.",
      status: "Delayed",
      priority: "High",
      progressPercentage: 30,
      dueDate: "2026-05-29",
      assignedToUserId: "u-2",
      assignedToUserName: "Mira Joshi",
      isOverdue: true,
      comments: [],
      subTasks: [],
    },
    {
      id: "task-3",
      projectId: "prj-3",
      milestoneId: "ms-4",
      title: "Build compact task expansion",
      description: "Support inline progress edits, comments, subtasks, and modal detail views.",
      status: "InProgress",
      priority: "Medium",
      progressPercentage: 74,
      dueDate: "2026-06-03",
      assignedToUserId: "u-3",
      assignedToUserName: "Sara Rao",
      comments: [],
      subTasks: [
        {
          id: "sub-3",
          parentTaskId: "task-3",
          projectId: "prj-3",
          milestoneId: "ms-4",
          title: "Wire progress slider",
          status: "Completed",
          priority: "Medium",
          progressPercentage: 100,
          comments: [],
        },
        {
          id: "sub-4",
          parentTaskId: "task-3",
          projectId: "prj-3",
          milestoneId: "ms-4",
          title: "Show profile with comments",
          status: "InProgress",
          priority: "Medium",
          progressPercentage: 65,
          comments: [],
        },
      ],
    },
  ],
  users: [
    {
      id: "u-admin",
      fullName: "Demo Director",
      email: "demo@pmwds.local",
      departmentId: "dept-1",
      roles: ["SuperAdmin", "Director"],
      departments: [{ departmentId: "dept-1", departmentName: "Platform", departmentCode: "PLT", organizationId: "org-1", organizationName: "North Grid Authority", isPrimary: true }],
    },
    { id: "u-1", fullName: "Asha Kapoor", email: "asha@pmwds.local", departmentId: "dept-1", roles: ["ProjectManager"] },
    { id: "u-2", fullName: "Mira Joshi", email: "mira@pmwds.local", departmentId: "dept-2", roles: ["DepartmentHead"] },
    { id: "u-3", fullName: "Sara Rao", email: "sara@pmwds.local", departmentId: "dept-3", roles: ["TeamMember"] },
  ],
};
